---
title: "IMI_ole_x_Treatment"
author: "Kaitlyn Campbell"
date: "1/15/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---
# Load packages and data
```{r}
library(brms)
library(dplyr)
library(ggplot2)
library(tibble)  
library(tidyverse)
library(readr)
library(faintr)
library(devtools)
library(rstan)
library(rstantools)
library(readr)
library(tidybayes)
library(bayesplot)

lab <- read_csv("/Users/kaitlyn.campbell/OneDrive - The University of South Dakota/Dissertation/Chapter4_Brains_IMI/Brain_IMI_Data.csv")

#View(lab)
lab$Treatment <- as.factor(lab$Treatment)

# Rename Mass_g_date columns with just the date
lab <- lab %>% 
  rename(June_26 = Mass_g_June_26) %>% 
  rename(July_3 = Mass_g_July_3) %>% 
  rename(July_10 = Mass_g_July_10) %>% 
  rename(July_17 = Mass_g_July_17)

# Need to add 0.000001 to all IMI_ng_mg_protein values b/c gamma distributions only take values larger than 0
lab_ole <- lab %>% 
  mutate(IMI_ole = IMI_ole_ng_mg_protein + 0.000001)
```

# based on model_selection_imi_ole.Rmd, fitole35 is the best fit
```{r}
# load model
load("/Users/kaitlyn.campbell/OneDrive - The University of South Dakota/Dissertation/Chapter4_Brains_IMI/Lab/Bayes_code/saved_models/fitole35.rda")

fitole35 <- brm(IMI_ole ~ Treatment, data = lab_ole, family = skew_normal(),
                prior=c(prior(normal(2, 1), class=Intercept),
                        prior(normal(0, 1), class = b, coef="Treatment0.1"),
                        prior(normal(2, 2), class = b, coef="Treatment1"),
                        prior(normal(5, 2), class = b, coef="Treatment5"),
                        prior(normal(10, 2), class = b, coef="Treatment10"),
                        prior(cauchy(0, 2), class = sigma),
                        prior(normal(1, 4), class= alpha)),
               iter = 3000 , warmup = 800, chains = 4, cores = 4,
               seed = 5, control = list(adapt_delta = 0.999), 
               save_pars = save_pars(all = TRUE))

save(fitole35, file = "/Users/kaitlyn.campbell/OneDrive - The University of South Dakota/Dissertation/Chapter4_Brains_IMI/Lab/Bayes_code/saved_models/fitole35.rda")

conditional_effects(fitole35)
```

# Extract posteriors
```{r}
set.seed(4545)
post_fit_ole <- posterior_samples(fitole35)  # puts chains of model into data frame
head(post_fit_ole)
nrow(post_fit_ole) # 8800
```

# Compute averages for each treatment category
```{r}
as_tibble(post_fit_ole) %>% 
  mutate(iteration = 1:nrow(post_fit_ole))

mu_0_ole <- data.frame(IMI_ole = post_fit_ole$b_Intercept, type = "0", 
                        iter = 1:nrow(post_fit_ole))

mu_0.1_ole <- data.frame(IMI_ole = post_fit_ole$b_Intercept +
                                          post_fit_ole$b_Treatment0.1, type = "0.1", 
                          iter = 1:nrow(post_fit_ole))

mu_1_ole <- data.frame(IMI_ole = post_fit_ole$b_Intercept + 
                                        post_fit_ole$b_Treatment1, 
                        type = "1", iter = 1:nrow(post_fit_ole))

mu_5_ole <- data.frame(IMI_ole = post_fit_ole$b_Intercept + 
                                        post_fit_ole$b_Treatment5, type = "5", iter = 1:nrow(post_fit_ole))

mu_10_ole <- data.frame(IMI_ole = post_fit_ole$b_Intercept+post_fit_ole$b_Treatment10,
                         type = "10", iter = 1:nrow(post_fit_ole))

ole_trt <- rbind(mu_0_ole, mu_0.1_ole, mu_1_ole, mu_5_ole, mu_10_ole)
```

# Summary stats from posterior with 89% CI
```{r}
ole_trt_summary <- ole_trt %>% 
  group_by(type) %>% 
  summarize(mean = mean(IMI_ole),
            median= median(IMI_ole),
            sd = sd(IMI_ole),
            low89 = quantile(IMI_ole, probs = 0.045),
            high89 = quantile(IMI_ole, probs = 0.955)) %>%
  mutate_if(is.numeric,round,2)

ole_trt_summary
```

# Visualize probability mass
```{r}
# add color palette
colorpalette <- c("#8d96a3","#66a182","#edae49","#6699CC","#d1495b")

ole_trt_df <- as.data.frame(ole_trt)

# plot
ole_p <- ggplot() +
  geom_violin(data=ole_trt, aes(x=type, y=IMI_ole, fill=type), position = "dodge") +
  geom_boxplot(data=ole_trt, aes(x=type, y=IMI_ole, fill=type), 
             outlier.shape = NA, width = 0.1, position = position_dodge(0.9)) +
  geom_jitter(data=lab_ole, aes(x=Treatment, y=IMI_ole_ng_mg_protein), size=0.8, shape=1, width = 0.25) + 
  #scale_y_log10() +
  labs(x = "Treatment (µg/L)",
       y = "Imidacloprid Olefin\nBrain Concentration \n(pg/mg protein)",
       fill= "Treatment (µg/L)") +
  theme_classic() + scale_fill_manual(values=colorpalette) + theme(plot.caption = element_text(hjust = 0))+ theme(axis.text.x = element_text(color="black", size="10"))+
  theme(axis.text.y = element_text(color="black", size="10"))+
  theme(legend.title = element_text(face="bold", size="10"))
ole_p

#ggsave("/Users/kaitlyn.campbell/OneDrive - The University of South Dakota/Dissertation/Chapter4_Brains_IMI/Lab/Bayes_code/plots/ole_p.tiff", ole_p, dpi=400, width=5, height=3, units="in")
```

# Group differences w/ 89% CI
```{r}
group_diffs_imi_ole <- ole_trt_summary %>% 
  mutate(diff_means = mean - lead(mean))
group_diffs_imi_ole
```
  type   mean median    sd low89 high89 diff_means
1 0      2.76   2.77  0.62  1.47   3.96       1.16
2 0.1    1.6    1.66  0.9  -0.33   3.21      -0.75
3 1      2.35   2.41  0.75  0.73   3.7       -4.66
4 5      7.01   7.04  0.82  5.36   8.6       -7.72
5 10    14.7   14.7   0.82 13.1   16.3       NA  

# Difference between trts
```{r}
# 0 µg/L and 0.1 µg/L treatments
dif_0_0.1 <- post_fit_ole %>% 
  transmute(dif = (b_Intercept) - (b_Intercept + b_Treatment0.1))
mean(dif_0_0.1$dif)  # 0.4555055
quantile(dif_0_0.1$dif,probs=c(0.045,0.955)) # (-0.8119722 , 1.7528482)
sum(dif_0_0.1$dif>0)/8800   ## 0.7278409

# 0.1 µg/L and 1 µg/L treatments
dif_0.1_1 <- post_fit_ole %>% 
  transmute(dif = (b_Intercept + b_Treatment1) - (b_Intercept + b_Treatment0.1))
mean(dif_0.1_1$dif)   # 0.6387256
quantile(dif_0.1_1$dif,probs=c(0.045,0.955)) # (-0.9780322 , 2.2779053)
sum(dif_0.1_1$dif>0)/8800  # 0.7542045

# 0 µg/L and 1 µg/L treatments
dif_0_1 <- post_fit_ole %>% 
  transmute(dif = (b_Intercept + b_Treatment1) - (b_Intercept))
mean(dif_0_1$dif)   # 0.1832201
quantile(dif_0_1$dif,probs=c(0.045,0.955)) # (-1.363798 , 1.721103)
sum(dif_0_1$dif>0)/8800   # 0.5807955

# 0 µg/L and 5 µg/L treatments
dif_0_5 <- post_fit_ole %>% 
  transmute(dif = (b_Intercept + b_Treatment5) - (b_Intercept))
mean(dif_0_5$dif)   # 5.119158
quantile(dif_0_5$dif,probs=c(0.045,0.955)) # (3.401266 , 6.856112)
sum(dif_0_5$dif>0)/8800 # 1

# 0 µg/L and 10 µg/L treatments
dif_0_10 <- post_fit_ole %>% 
  transmute(dif = (b_Intercept + b_Treatment10) - (b_Intercept))
mean(dif_0_10$dif) ## 12.83003
quantile(dif_0_10$dif,probs=c(0.045,0.955)) # (11.06244 , 14.63616)
sum(dif_0_10$dif>0)/8800 # 1

# 10 µg/L and 0.1 µg/L treatments
dif_10_0.1 <- post_fit_ole %>% 
  transmute(dif = (b_Intercept + b_Treatment10) - (b_Intercept + b_Treatment0.1))
mean(dif_10_0.1$dif) ## 13.28554
quantile(dif_10_0.1$dif,probs=c(0.045,0.955)) # (11.33796 , 15.32299)
sum(dif_10_0.1$dif>0)/8800 # 1

# 10 µg/L and 5 µg/L treatments
dif_10_5 <- post_fit_ole %>% 
  transmute(dif = (b_Intercept + b_Treatment10) - (b_Intercept + b_Treatment5))
mean(dif_10_5$dif) ## 7.710872
quantile(dif_10_5$dif,probs=c(0.045,0.955)) # (5.810894 , 9.590526)
sum(dif_10_5$dif>0)/8800 # 1

# 5 µg/L and 1 µg/L treatments
dif_5_1 <- post_fit_ole %>% 
  transmute(dif = (b_Intercept + b_Treatment5) - (b_Intercept + b_Treatment1))
mean(dif_5_1$dif) ## 4.935937
quantile(dif_5_1$dif,probs=c(0.045,0.955)) # (3.112680 , 6.879354)
sum(dif_5_1$dif>0)/8800 # 1

# 5 µg/L and 0.1 µg/L treatments
dif_5_0.1 <- post_fit_ole %>% 
  transmute(dif = (b_Intercept + b_Treatment5) - (b_Intercept + b_Treatment0.1))
mean(dif_5_0.1$dif) ## 5.574663
quantile(dif_5_0.1$dif,probs=c(0.045,0.955)) # (3.732806 , 7.482773)
sum(dif_5_0.1$dif>0)/8800 # 1
```
